version: '3.8'

services:
#  db:
#    image: postgres
#    env_file: .env
##    environment:
##      - POSTGRES_DB=diplom_project
##      - POSTGRES_USER=postgres
##      - POSTGRES_PASSWORD=postgres
#    container_name: db
#    volumes:
#      - postgres_data:/var/lib/postgresql/data
#    ports:
#      - 5432:5432

  redis:
    image: redis
    env_file: .env
    container_name: redis
    volumes:
      - redis_data:/data
    ports:
      - 6379:6379

#  backend:
#    build: .
#    command:
#      - sh
#      - -c
#      - |
#        python manage.py makemigrations backend --noinput
#        python manage.py migrate
#        python manage.py runserver 0.0.0.0:8000
#    volumes:
#      - .:/orders
#    ports:
#      - 8000:8000
#    depends_on:
#      - db
#      - redis
#
#  pgadmin:
#    image: dpage/pgadmin4
#    environment:
#      - PGADMIN_DEFAULT_EMAIL=admin@yandex.ru
#      - PGADMIN_DEFAULT_PASSWORD=admin1pwd
#      - PGADMIN_CONFIG_SERVER_MODE=False
#    volumes:
#      - pgadmin:/var/lib/pgadmin
#    restart: unless-stopped
#    ports:
#      - 5050:80
#
#  worker:
#    build:
#      context: .
#    depends_on: :
#      - redis
#    volumes:
#      - .:/orders
#    command: celery -A orders.celery.app worker --loglevel=INFO

volumes:
  postgres_data:
  redis_data: