# Generated by Django 5.0.1 on 2024-02-10 14:28

import imagekit.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="avatar_thumbnail",
            field=imagekit.models.fields.ProcessedImageField(
                blank=True, null=True, upload_to="avatar"
            ),
        ),
    ]
