# Generated by Django 5.0.1 on 2024-01-28 15:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="shop",
            name="status",
            field=models.CharField(
                choices=[("OP", "Open"), ("CL", "Close")], default="OP", max_length=2
            ),
        ),
        migrations.AddField(
            model_name="shop",
            name="user",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
