# примеры API-запросов

@baseUrl = http://localhost:8000/backend

# получение магазинов
GET {{baseUrl}}/shops/
Content-Type: application/json

###

# получение категорий
GET {{baseUrl}}/categories/
Content-Type: application/json

###

# получение продуктов
GET {{baseUrl}}/products/
Content-Type: application/json

###
# получение контактов
GET {{baseUrl}}/contact/
Content-Type: application/json
Authorization: Token 37273f6fa092ad4e5f91ada1aa65bc1b8f34aaf1

###

# создание контакта
POST {{baseUrl}}/contact/
Content-Type: application/json
Authorization: Token 37273f6fa092ad4e5f91ada1aa65bc1b8f34aaf1

{
  "phone": "89001234567",
  "city": "Moscow",
  "street": "Tverskaya",
  "house": "10",
  "building": "1",
  "structure": "2",
  "apartment": "124"
}

###

# изменение контакта
PUT {{baseUrl}}/contact/
Content-Type: application/json
Authorization: Token 37273f6fa092ad4e5f91ada1aa65bc1b8f34aaf1

{
  "contact_id": "1",
  "phone": "87598598",
  "city": "Moscow",
  "street": "Tverskaya",
  "house": "10",
  "building": "1",
  "structure": "2",
  "apartment": "100"

}

###

# удаление контакта
DELETE {{baseUrl}}/contact/
Content-Type: application/json
Authorization: Token 37273f6fa092ad4e5f91ada1aa65bc1b8f34aaf1

{
  "contact_id": "1"
}

###

# получение информации о продукте
GET {{baseUrl}}/product_info?shop_id=2&product_id=4216292
Content-Type: application/json

###

# регистрация пользователя
POST {{baseUrl}}/register/
Content-Type: application/json

{
  "first_name": "max",
  "last_name": "tols",
  "email": "tolstikov-95@inbox.ru",
  "password": "admin1234567",
  "username": "admin123",
  "type": "SP"
}

###

# подтверждение пользователя
POST {{baseUrl}}/confirm/
Content-Type: application/json

{
  "email": "tolstikov-95@inbox.ru",
  "token": "6fcbfd8ad074"
}

###

# логин пользователя
POST {{baseUrl}}/login/
Content-Type: application/json

{
  "email": "tolstikov-95@inbox.ru",
  "password": "admin1234567"
}

###

# детали пользователя
GET {{baseUrl}}/account/
Content-Type: application/json
Authorization: Token 37273f6fa092ad4e5f91ada1aa65bc1b8f34aaf1

###

# изменение деталей пользователя
POST {{baseUrl}}/account/
Content-Type: application/json
Authorization: Token 37273f6fa092ad4e5f91ada1aa65bc1b8f34aaf1

{
  "first_name": "maxsy",
  "last_name": "tolsy",
  "email": "tolstikov-995@inbox.ru",
  "password": "admin1234567",
  "username": "admin1234"
}


###############


# получение товаров из корзины
GET {{baseUrl}}/basket/
Content-Type: application/json
Authorization: Token 37273f6fa092ad4e5f91ada1aa65bc1b8f34aaf1

###

# добавление товаров в корзину
POST {{baseUrl}}/basket/
Content-Type: application/json
Authorization: Token 37273f6fa092ad4e5f91ada1aa65bc1b8f34aaf1

{
  "product_info": 3,
  "quantity": 2
}

###

# редактирование товаров корзины
PUT {{baseUrl}}/basket/
Content-Type: application/json
Authorization: Token 37273f6fa092ad4e5f91ada1aa65bc1b8f34aaf1

{
  "id": 4,
  "quantity": 20
}

###

# удаление товаров из корзины
DELETE {{baseUrl}}/basket/
Content-Type: application/json
Authorization: Token 37273f6fa092ad4e5f91ada1aa65bc1b8f34aaf1

{
  "id": 19
}

###

# получение заказов
GET {{baseUrl}}/order/
Content-Type: application/json
Authorization: Token 37273f6fa092ad4e5f91ada1aa65bc1b8f34aaf1

###

# размещение заказов
POST {{baseUrl}}/order/
Content-Type: application/json
Authorization: Token 37273f6fa092ad4e5f91ada1aa65bc1b8f34aaf1

{
  "id": 3,
  "contact": 2
}

###

# получение заказов магазином
GET {{baseUrl}}/shop/orders/
Content-Type: application/json
Authorization: Token 3eca308830f5b493f5324074ddcbe40976169843

###

# получение статуса магазина
GET {{baseUrl}}/shop/status/
Content-Type: application/json
Authorization: Token 3eca308830f5b493f5324074ddcbe40976169843

###

# изменение статуса магазина

POST {{baseUrl}}/shop/status/
Content-Type: application/json
Authorization: Token 3eca308830f5b493f5324074ddcbe40976169843
