# примеры API-запросов

@baseUrl = http://localhost:8000/backend


# регистрация пользователя
POST {{baseUrl}}/user/register/
Content-Type: application/json

{
  "first_name": "Maksim",
  "last_name": "Tolstikov",
  "email": "tolstikov-95@inbox.ru", 
  "password": "qwerty_123",
  "username": "tolstikov-95",
  "phone": "89001234567",
  "type": "BR"
}

###

# подтверждение пользователя
POST {{baseUrl}}/user/register/confirm/
Content-Type: application/json

{
  "email": "tolstikov-95@inbox.ru", 
  "token": "f0725b610a225d65cf846324d051e453a"
}

###

# логин пользователя
POST {{baseUrl}}/user/login/
Content-Type: application/json

{
  "email": "tolstikov-95@inbox.ru",
  "password": "qwerty_123"
}

###

# детали пользователя
GET {{baseUrl}}/user/details/
Content-Type: application/json
Authorization: Token 37273f6fa092ad4e5f91ada1aa65bc1b8f34aaf1

###

# изменение деталей пользователя
POST {{baseUrl}}/user/details/
Content-Type: application/json
Authorization: Token 37273f6fa092ad4e5f91ada1aa65bc1b8f34aaf1

{
  "first_name": "Max",
  "last_name": "Tols",
  "email": "tolstikov-9995@inbox.ru", 
  "password": "qwerty_12345",
  "phone": "87598598",
  "username": "max-tols"
}


###

# получение контактов
GET {{baseUrl}}/user/contact/
Content-Type: application/json
Authorization: Token 37273f6fa092ad4e5f91ada1aa65bc1b8f34aaf1

###

# создание контакта
POST {{baseUrl}}/user/contact/
Content-Type: application/json
Authorization: Token 37273f6fa092ad4e5f91ada1aa65bc1b8f34aaf1

{
  "city": "Moscow",
  "street": "Tverskaya",
  "house": "10",
  "building": "1",
  "structure": "2",
  "apartment": "12"
}

###

# изменение контакта
PUT {{baseUrl}}/user/contact/
Content-Type: application/json
Authorization: Token 37273f6fa092ad4e5f91ada1aa65bc1b8f34aaf1

{
  "contact_id": "1",
  "city": "Moscow",
  "street": "Arbat",
  "house": "8",
  "building": "2",
  "structure": "12",
  "apartment": "97"
}

###

# удаление контакта
DELETE {{baseUrl}}/user/contact/
Content-Type: application/json
Authorization: Token 37273f6fa092ad4e5f91ada1aa65bc1b8f34aaf1

{
  "contact_id": "1"
}

###

# восстановление пользователя
POST {{baseUrl}}/user/reset_password/
Content-Type: application/json

{  
  "email": "tolstikov-95@inbox.ru"
}

###

# повторное подтверждение пользователя
POST {{baseUrl}}/user/reset_password/confirm/
Content-Type: application/json

{
  "email": "tolstikov-95@inbox.ru",
  "password": "qwerty_123",
  "token": "2dbbcb7c484f03de95fbd486ca962325f2"
}

###

# загрузка данных магазина
POST {{baseUrl}}/seller/update/
Content-Type: application/json
Authorization: Token 273f6fa092ad4e5f91ada1aa65bc1b8f34aaf1

{
  "url": "https://raw.githubusercontent.com/netology-code/pd-diplom/master/data/shop1.yaml"
}

###

# получение статуса магазина
GET {{baseUrl}}/seller/status/
Content-Type: application/json
Authorization: Token 273f6fa092ad4e5f91ada1aa65bc1b8f34aaf1

###

# автоматическое изменение статуса магазина
POST {{baseUrl}}/seller/status/
Content-Type: application/json
Authorization: Token 273f6fa092ad4e5f91ada1aa65bc1b8f34aaf1

###

# получение заказов магазином
GET {{baseUrl}}/seller/orders/
Content-Type: application/json
Authorization: Token 273f6fa092ad4e5f91ada1aa65bc1b8f34aaf1

###

# получение магазинов
GET {{baseUrl}}/shops/
Content-Type: application/json

###

# получение категорий
GET {{baseUrl}}/categories/
Content-Type: application/json

###

# получение продуктов
GET {{baseUrl}}/products/
Content-Type: application/json

###

# получение информации о продукте
GET {{baseUrl}}/product_info?shop_id=1&product_id=1
Content-Type: application/json

###

# получение товаров из корзины
GET {{baseUrl}}/basket/
Content-Type: application/json
Authorization: Token 37273f6fa092ad4e5f91ada1aa65bc1b8f34aaf1

###

# добавление товаров в корзину
POST {{baseUrl}}/basket/
Content-Type: application/json
Authorization: Token 37273f6fa092ad4e5f91ada1aa65bc1b8f34aaf1

{
  "items": 
    [{"product_info": 1, "quantity": 4}, {"product_info": 2, "quantity": 1}]
}

###

# редактирование товаров корзины
PUT {{baseUrl}}/basket/
Content-Type: application/json
Authorization: Token 37273f6fa092ad4e5f91ada1aa65bc1b8f34aaf1

{
  "items": 
    [{"id": 1, "quantity": 1}, {"id": 2, "quantity": 2}]
}

###

# удаление товаров из корзины
DELETE {{baseUrl}}/basket/
Content-Type: application/json
Authorization: Token 37273f6fa092ad4e5f91ada1aa65bc1b8f34aaf1

{
  "items": "1"
}

###

# получение заказов
GET {{baseUrl}}/order/
Content-Type: application/json
Authorization: Token 37273f6fa092ad4e5f91ada1aa65bc1b8f34aaf1

###

# размещение заказов
POST {{baseUrl}}/order/
Content-Type: application/json
Authorization: Token 37273f6fa092ad4e5f91ada1aa65bc1b8f34aaf1

{
  "id": 1, 
  "contact": 2
}
